# Generated by Django 4.0.2 on 2022-02-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DodatakNapitak",
            new_name="DodatakStavka",
        ),
        migrations.RemoveField(
            model_name="napitak",
            name="dodatak",
        ),
        migrations.RemoveField(
            model_name="stavka",
            name="cijena",
        ),
        migrations.AddField(
            model_name="stavka",
            name="dodatak",
            field=models.ManyToManyField(blank=True, to="Aparat.Dodaci"),
        ),
        migrations.AlterField(
            model_name="dodatakstavka",
            name="napitak",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Aparat.stavka"
            ),
        ),
    ]
