# Generated by Django 4.0.2 on 2022-02-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0002_rename_dodataknapitak_dodatakstavka_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="napitak",
            name="vrijeme_isporuke",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="narudzba",
            name="vrijeme_kupnje",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
