# Generated by Django 4.0.2 on 2022-02-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0004_remove_napitak_vrijeme_isporuke_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narudzba",
            name="vrijeme_isporuke",
            field=models.TimeField(null=True),
        ),
    ]
