# Generated by Django 4.0.2 on 2022-02-19 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0005_alter_narudzba_vrijeme_isporuke"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="narudzba",
            name="id",
        ),
        migrations.AlterField(
            model_name="narudzba",
            name="broj_narudzbe",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
