# Generated by Django 4.0.2 on 2022-02-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0006_remove_narudzba_id_alter_narudzba_broj_narudzbe"),
    ]

    operations = [
        migrations.AddField(
            model_name="narudzba",
            name="adresa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="narudzba",
            name="grad",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
