# Generated by Django 4.0.2 on 2022-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0008_napitak_slika"),
    ]

    operations = [
        migrations.AddField(
            model_name="dodaci",
            name="slika",
            field=models.ImageField(default="default_dodaci.jpg", upload_to="dodaci/"),
        ),
        migrations.AlterField(
            model_name="dodaci",
            name="naziv",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="napitak",
            name="slika",
            field=models.ImageField(default="default_drink.jpg", upload_to="pica/"),
        ),
        migrations.AlterField(
            model_name="napitak",
            name="vrsta_napitka",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="salica",
            name="materijal",
            field=models.CharField(max_length=255),
        ),
    ]
