# Generated by Django 4.0.2 on 2022-02-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0009_dodaci_slika_alter_dodaci_naziv_alter_napitak_slika_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="narudzba",
            name="ime_i_prezime",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
