# Generated by Django 4.0.2 on 2022-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0010_narudzba_ime_i_prezime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="napitak",
            name="toplo_hladno",
        ),
        migrations.AddField(
            model_name="stavka",
            name="toplo_hladno",
            field=models.BooleanField(default=True),
        ),
    ]
