# Generated by Django 4.0.2 on 2022-02-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0011_remove_napitak_toplo_hladno_stavka_toplo_hladno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stavka",
            old_name="toplo_hladno",
            new_name="toplo",
        ),
    ]
