# Generated by Django 4.0.2 on 2022-02-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Aparat", "0012_rename_toplo_hladno_stavka_toplo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dodaci",
            options={"verbose_name": "Dodatak", "verbose_name_plural": "Dodaci"},
        ),
        migrations.AlterModelOptions(
            name="napitak",
            options={"verbose_name": "Napitci", "verbose_name_plural": "Napitak"},
        ),
        migrations.AlterModelOptions(
            name="narudzba",
            options={"verbose_name": "Narudžba", "verbose_name_plural": "Narudžbe"},
        ),
        migrations.AlterModelOptions(
            name="salica",
            options={"verbose_name": "Šalica", "verbose_name_plural": "Šalice"},
        ),
        migrations.AlterModelOptions(
            name="stavka",
            options={"verbose_name": "Stavka", "verbose_name_plural": "Stavke"},
        ),
    ]
